### ISSUE TITLE
Borrar archivos vacios

### ISSUE THREAD

**Issue by KatuGT** [joaquinpavon22/Turismo-y-gastronomia#10]
![image](https://github.com/user-attachments/assets/bb3f0fd4-dc7f-4733-a9cf-229e5f137b73)

Por ejemplo archivo, si no tiene proposito, nos deshagamos de el

**Comment by joaquinpavon22** [comment]
corregida

**Comment by KatuGT** [comment]
@joaquinpavon22 
![image](https://github.com/user-attachments/assets/73d6b897-415f-44a7-bdad-3b17741e6099)
ese archivo vacío lo sigo viendo en la rama Main

**Comment by joaquinpavon22** [comment]
Por alguna razón o error no se borro en el ultimo commit, puedes reviarr ahora por favor

**Comment by KatuGT** [comment]
listo!
