### ISSUE TITLE
Borrar imagenes sin  uso

### ISSUE THREAD

**Issue by KatuGT** [joaquinpavon22/Turismo-y-gastronomia#11]
![image](https://github.com/user-attachments/assets/066bdc2c-f804-420c-8424-d28990330f59)

Hablando de la imagen 404-error, veo que estan haciendo uso del archivo 404-Error (1).jpg, borremos el otro

y un comentario, recordemos que no es buena practica guardar archivos con espacios en sus nombres

**Comment by joaquinpavon22** [comment]
corregida

**Comment by KatuGT** [comment]
@joaquinpavon22 
![image](https://github.com/user-attachments/assets/c220c9d5-7eeb-4272-8f5f-42f9f462cf12)

aun veo que estan ambas imagenes, y figura que no se hicieron cambios hace 2 meses en esa carpeta, me parece que se les paso subir este cambio

**Comment by joaquinpavon22** [comment]
Por alguna razón o error no se borro en el ultimo commit, puedes reviarr ahora por favor

**Comment by KatuGT** [comment]
listo!
