### ISSUE TITLE
formatear documentos para "normalizar" codigo

### ISSUE THREAD

**Issue by KatuGT** [joaquinpavon22/Turismo-y-gastronomia#9]
![image](https://github.com/user-attachments/assets/17979e90-fb6c-4c0c-952c-9680ee6abc16)

Utilicemos el plugin de prittier  para acomodar las lineas de codigo, por ejemplo asi es como se ve actualmente uno de sus archivos css,

Luego de formatearlo se ve asi

![image](https://github.com/user-attachments/assets/19a8309e-39f5-40b7-837e-906991cf279c)

**Comment by joaquinpavon22** [comment]
corregida

**Comment by KatuGT** [comment]
muy bien
